env:
  browser: true
  commonjs: true
  es2021: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:unicorn/recommended'
parserOptions:
  ecmaVersion: 12
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - warn
    - double
  semi:
    - error
    - always
  no-unused-vars: warn
  comma-spacing: error
  camelcase: warn
  unicorn/consistent-function-scoping: warn
  unicorn/filename-case:
    - error
    - case: camelCase
  unicorn/prefer-query-selector: warn
  unicorn/prefer-dom-node-dataset: off
